---
#httpd installation
- name: httpd installation
  hosts: node02
  tasks:
    - name: install httpd
      yum: name=httpd
    - name: enabled and start httpd
      service: name=httpd enabled=true state=started 
    - name: create index.html
      copy:
        content: "welcome to my web server"
        dest: /var/www/html/index.html
        mode: 0444
    - name: open firewall port
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
...
