---
- name: creating group and user
  hosts: one
  become: yes
  vars_files: 
  - vars/node01.yml
  tasks:
    - name: create group
      group:
          name: dev
          state: present
    - name: creating user
      user: 
          name: "{{ item.name }}"
          password: "{{ item.pw | password_hash('sha512')}}"
          groups: dev
          state: present
      with_items: "{{ newusers }}"

          
